### ISSUE TITLE
Interest in a refactor of the installation script?

### ISSUE THREAD

**Issue by jiblits** [yjx1217/LRSDAY#1]
I found that getting the install script to work in one-shot to be a bit tricky so I've been refactoring it to try and reduce some duplication as well as make it more straightforward to install on a fresh system.

My deployment scenario is on-demand cloud services. Basically the script runs, it installs all the system requirements followed by all the other LRSDAY dependencies within the script. The script also attempts to mark what has been installed to avoid building programs that have already been successful.

**Comment by yjx1217** [comment]
Hi @jiblits , 

Sure, it will be great if we can make the installation process more robust. Thank you very much for spending time and efforts to improve it. When your modified installation script is ready, you can send it to me via email (yuejiaxing[at]gmail[dot]com). I will make more tests with it using different servers that I can access to. Once we finish all the tests, we can adopt this new installation script for a more smooth installation experience. Thanks again!

Best,
Jia-Xing

**Comment by jiblits** [comment]
Would a pull request be OK?

**Comment by yjx1217** [comment]
Sure, please go ahead.

Best,
Jia-Xing

**Comment by yjx1217** [comment]
The changes have been merged into the base branch. Thanks again for the contribution! I am closing this issue report now.
