### ISSUE TITLE
MFANNOT mtDNA annotation

### ISSUE THREAD

**Issue by nicolo-tellini** [yjx1217/LRSDAY#14]
Hello @yjx1217 ,

I'm currently using LRSDAY v1.72 and encountering the following problem during the mtDNA annotation phase.
Perhaps you've encountered this issue before.

```
1) Translate (flip)...
2) Blast...
3) Parse Blast Results...
4) Select best proteins for Exonerate...
5) Annotate genes w/o introns...
6) Intron identification...
Cannot read result for 'IntronI'; maybe there were problems with the commands?
Cannot read result for 'IntronII'; maybe there were problems with the commands?
7) Annotate genes with introns...
8) Identify gene fusions...
9) Annotate mini exons...
10) Annotate RNA genes...
    'rns'...
    'rnl'...
    'tRNA'...
Cannot read result for 'tRNA'; maybe there were problems with the commands?
    'rnpB'...
Cannot read result for 'rnpB'; maybe there were problems with the commands?
    'rrn5'...
Cannot read result for 'rrn5'; maybe there were problems with the commands?
11) Adjust intron boundaries...
12) Identify start codons; identify gene fusions...
13) Find extra genes with HMM
14) ORF annotation...
15) Intron ORF annotation...

```

thanks 

nic

**Comment by yjx1217** [comment]
Hi Nic,

No, it was OK on my side when I tested it a year ago.
```


----------------------------------
         Gene Annotation          
----------------------------------
Parsing masterfile CPG_1a.assembly.mitochondrial_genome.tidy.fa...

1) Translate (flip)...
2) Blast...
3) Parse Blast Results...
4) Select best proteins for Exonerate...
5) Annotate genes w/o introns...
6) Intron identification...
7) Annotate genes with introns...
8) Identify gene fusions...
9) Annotate mini exons...
10) Annotate RNA genes...
    'rns'...
    'rnl'...
    'tRNA'...
    'rnpB'...
    'rrn5'...
11) Adjust intron boundaries...
12) Identify start codons; identify gene fusions...
13) Find extra genes with HMM
14) ORF annotation...
15) Intron ORF annotation...

----------------------------------
       This is it, Folks !     
----------------------------------
```

So could you check if there is a recent version update for the dependencies of mfannot that the original LRSDAY installer script has not employed strict version control? I guess it is due to a recent version update of one or more of these mfannot dependencies that caused your problem.

Best,
Jia-Xing

**Comment by nicolo-tellini** [comment]
Hi @yjx1217 ,

Could you provide the versions of the following software for comparison with my current setup?

```
Blast
HMMER
Exonerate
Muscle
EMBOSS
Erpin
tbl2asn
PirObject
```

thanks

**Comment by yjx1217** [comment]
Hi Nic,

I've just finished an installation test on my side and found out the downloading urls for spades, repeatmasker, and tbl2asn will need to be changed in the install_dependencies.sh script. My installation and the test for mt genome annotation finished without any issue with these changes. I've just submitted a new commit to reflect these changes.

https://github.com/yjx1217/LRSDAY/commit/78d0b457394b3ac559e847eb5f6fe246eb5ed774

Best,
Jia-Xing

**Comment by nicolo-tellini** [comment]
Hello @yjx1217 ,

Yes, the errors occurred because chrMT was incorrectly labeled as >prefix_chrMT at a certain stage, resulting in chrMT FASTA being empty. Then, mfannot complained in the way I listed above (not really intuitive).

best 

nic

**Comment by yjx1217** [comment]
Hi Nic,

I guess you can use all PacBio HiFi reads directly for the assembly. No pre-filtering is necessary.

Best,
Jia-Xing

**Comment by nicolo-tellini** [comment]
Hello @yjx1217 ,

thanks, I clean this issue so there is a single topic and I close it.

best,

nic
