### ISSUE TITLE
logs and err - for the installer

### ISSUE THREAD

**Issue by nicolo-tellini** [yjx1217/LRSDAY#4]
Hello JX,

the installer runs several software. 

what about redirecting _logs_ and _errors_ output inside software-named _txt_ and storing them inside an appropriate folder?

For example

what if the main installer contains several ```.sh``` scripts each one installing a specific software ( for example: ```guppy.sh```) ?

Again, let's say ```guppy.sh``` contains :

```
#!/bin/bash

# common vars
LRSDAY_HOME=$(pwd)
build_dir=$LRSDAY_HOME"/build"

# specific vars
GUPPY_VERSION="4.0.15" # released on 2020.08.30
GUPPY_DOWNLOAD_URL="https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy-cpu_${GUPPY_VERSION}_linux64.tar.gz"

# software dir
guppy_dir="$build_dir/ont-guppy-cpu/bin"

if [ -z $(check_installed $guppy_dir) ]; then
   cd $build_dir
   echo "Download Guppy-v${GUPPY_VERSION}"
   download_and_extract $GUPPY_DOWNLOAD_URL "ont-guppy-cpu_${GUPPY_VERSION}_linux64.tar.gz"
   note_installed $guppy_dir 
fi
```
and the main installation script runs :

```
/usr/bin/time -v bash guppy.sh > $build_dir/logs/guppy.log 2> $build_dir/errs/guppy.err
```
At the end of the software installation ```.err``` files will contain, for example : 
```
	Command being timed: "bash  guppy.sh"
	User time (seconds): 53314.37
	System time (seconds): 43012.15
	Percent of CPU this job got: 2431%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:06:00
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 15448
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 2
	Minor (reclaiming a frame) page faults: 5286729714
	Voluntary context switches: 70514711
	Involuntary context switches: 1405776
	Swaps: 0
	File system inputs: 16
	File system outputs: 488704
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
After the ```bash  guppy.sh ```  the installation can be easily checked for the presence of errors as follow :

```
        check=$(grep Exit ${build_dir}/logs/guppy.err | cut -d":" -f2 | tr -d "[:blank:]")
	if [ $check == 1 ]
	then
	echo "Exit at guppy.sh"
	exit
	else
	echo "guppy.sh ... OK"	
	fi
```
This is a lot reorganization but it can make the installation process easier to debug. 

best,

Nic

**Comment by yjx1217** [comment]
Hi Nicolo,

Thanks for the issue reports and feedback. Yes, due to the rapid updates of some dependencies of LRSDAY, especially those related to long read processing, a systematic update will be needed for now to make it to work as smoothly as before. I am planning to apply a major update in this October to completely solve the issues. While I also want to apply such a fix sooner, the time constraint on my side right now doesn't allow me to do so. :( 

I will let you know when the updated version is ready.

Best,
Jia-Xing
