### ISSUE TITLE
Suggestion for adding a `conda install` yml support or docker installation 

### ISSUE THREAD

**Issue by likelet** [yjx1217/LRSDAY#8]
Hi Jiaxing

I noticed that this tool have a lot of dependencies for installation, which is not friendly for users with low linux use experience. 

May you provide a conda install yml file or docker image for an easy environment installation. 

Qi

**Comment by yjx1217** [comment]
Thanks for the suggestion! We have been considered this option but it will likely take time to be implemented. For now, we have provided an automatic installer script (install_dependencies.sh) to hopefully ease the installation process as much as possible. :-)

Best,
Jia-Xing
